/**
 * Localized city names for FR and ES.
 * English city names (from destinations.json) are used as fallback.
 * Usage: getLocalizedCityName(slug, englishName, locale)
 */

const NAMES_FR: Record<string, string> = {
  lisbon: 'Lisbonne',
  vienna: 'Vienne',
  edinburgh: 'Édimbourg',
  venice: 'Venise',
  florence: 'Florence',
  copenhagen: 'Copenhague',
  seville: 'Séville',
  valencia: 'Valence',
  granada: 'Grenade',
  como: 'Lac de Côme',
  ghent: 'Gand',
  antwerp: 'Anvers',
  warsaw: 'Varsovie',
  krakow: 'Cracovie',
  brussels: 'Bruxelles',
  athens: 'Athènes',
  salzburg: 'Salzbourg',
  barcelona: 'Barcelone',
  munich: 'Munich',
  cologne: 'Cologne',
  rome: 'Rome',
  milan: 'Milan',
  naples: 'Naples',
  dubrovnik: 'Dubrovnik',
  zagreb: 'Zagreb',
  bucharest: 'Bucarest',
  sofia: 'Sofia',
  oslo: 'Oslo',
  stockholm: 'Stockholm',
  helsinki: 'Helsinki',
  reykjavik: 'Reykjavik',
  geneva: 'Genève',
  zurich: 'Zurich',
  luxembourg: 'Luxembourg',
  nice: 'Nice',
  lyon: 'Lyon',
  bordeaux: 'Bordeaux',
  toulouse: 'Toulouse',
  bruges: 'Bruges',
  porto: 'Porto',
  bilbao: 'Bilbao',
  tallinn: 'Tallinn',
  riga: 'Riga',
  vilnius: 'Vilnius',
  budapest: 'Budapest',
  bratislava: 'Bratislava',
  ljubljana: 'Ljubljana',
  thessaloniki: 'Thessalonique',
  bern: 'Berne',
  london: 'Londres',
  hamburg: 'Hambourg',
  hannover: 'Hanovre',
  frankfurt: 'Francfort',
  turin: 'Turin',
  verona: 'Vérone',
  bologna: 'Bologne',
  prague: 'Prague',
  marseille: 'Marseille',
  malaga: 'Malaga',
  'san-sebastian': 'Saint-Sébastien',
}

const NAMES_ES: Record<string, string> = {
  lisbon: 'Lisboa',
  vienna: 'Viena',
  edinburgh: 'Edimburgo',
  florence: 'Florencia',
  venice: 'Venecia',
  ghent: 'Gante',
  antwerp: 'Amberes',
  warsaw: 'Varsovia',
  krakow: 'Cracovia',
  brussels: 'Bruselas',
  athens: 'Atenas',
  salzburg: 'Salzburgo',
  seville: 'Sevilla',
  como: 'Lago de Como',
  copenhagen: 'Copenhague',
  munich: 'Múnich',
  cologne: 'Colonia',
  rome: 'Roma',
  milan: 'Milán',
  naples: 'Nápoles',
  zagreb: 'Zagreb',
  bucharest: 'Bucarest',
  sofia: 'Sofía',
  geneva: 'Ginebra',
  zurich: 'Zúrich',
  nice: 'Niza',
  bruges: 'Brujas',
  tallinn: 'Tallin',
  riga: 'Riga',
  vilnius: 'Vilna',
  bratislava: 'Bratislava',
  ljubljana: 'Liubliana',
  thessaloniki: 'Tesalónica',
  bern: 'Berna',
  reykjavik: 'Reikiavik',
  london: 'Londres',
  hamburg: 'Hamburgo',
  frankfurt: 'Fráncfort',
  turin: 'Turín',
  verona: 'Verona',
  bologna: 'Bolonia',
  prague: 'Praga',
  malaga: 'Málaga',
  'san-sebastian': 'San Sebastián',
}

const NAMES_PT: Record<string, string> = {
  lisbon: 'Lisboa',
  vienna: 'Viena',
  edinburgh: 'Edimburgo',
  florence: 'Florença',
  venice: 'Veneza',
  ghent: 'Gante',
  antwerp: 'Antuérpia',
  warsaw: 'Varsóvia',
  krakow: 'Cracóvia',
  brussels: 'Bruxelas',
  athens: 'Atenas',
  salzburg: 'Salzburgo',
  seville: 'Sevilha',
  copenhagen: 'Copenhaga',
  munich: 'Munique',
  cologne: 'Colónia',
  rome: 'Roma',
  milan: 'Milão',
  naples: 'Nápoles',
  zagreb: 'Zagreb',
  bucharest: 'Bucareste',
  sofia: 'Sófia',
  geneva: 'Genebra',
  zurich: 'Zurique',
  nice: 'Nice',
  bruges: 'Bruges',
  tallinn: 'Talim',
  riga: 'Riga',
  vilnius: 'Vilnius',
  bratislava: 'Bratislava',
  ljubljana: 'Liubliana',
  thessaloniki: 'Salónica',
  bern: 'Berna',
  reykjavik: 'Reiquiavique',
  london: 'Londres',
  hamburg: 'Hamburgo',
  frankfurt: 'Frankfurt',
  turin: 'Turim',
  verona: 'Verona',
  bologna: 'Bolonha',
  prague: 'Praga',
  malaga: 'Málaga',
  'san-sebastian': 'San Sebastián',
  barcelona: 'Barcelona',
  madrid: 'Madrid',
  paris: 'Paris',
  marseille: 'Marselha',
  lyon: 'Lyon',
  toulouse: 'Toulouse',
  strasbourg: 'Estrasburgo',
  bordeaux: 'Bordéus',
  nantes: 'Nantes',
  lille: 'Lille',
  rotterdam: 'Roterdão',
  amsterdam: 'Amesterdão',
  'the-hague': 'Haia',
  utrecht: 'Utreque',
  maastricht: 'Maastricht',
  luxembourg: 'Luxemburgo',
  dublin: 'Dublin',
  cork: 'Cork',
  galway: 'Galway',
  belgrade: 'Belgrado',
  split: 'Split',
  dubrovnik: 'Dubrovnik',
  helsinki: 'Helsínquia',
  stockholm: 'Estocolmo',
  oslo: 'Oslo',
  bergen: 'Bergen',
  trondheim: 'Trondheim',
  stavanger: 'Stavanger',
  cordoba: 'Córdova',
  granada: 'Granada',
  valencia: 'Valência',
  como: 'Lago de Como',
  palma: 'Palma',
  bilbao: 'Bilbau',
  toledo: 'Toledo',
  zaragoza: 'Saragoça',
  salamanca: 'Salamanca',
  porto: 'Porto',
  faro: 'Faro',
  evora: 'Évora',
  coimbra: 'Coimbra',
  nuremberg: 'Nuremberga',
  graz: 'Graz',
  innsbruck: 'Innsbruck',
  brno: 'Brno',
  gdansk: 'Gdansk',
  wroclaw: 'Wroclaw',
}

export function getLocalizedCityName(
  slug: string,
  englishName: string,
  locale: string
): string {
  if (locale === 'fr') return NAMES_FR[slug] ?? englishName
  if (locale === 'es') return NAMES_ES[slug] ?? englishName
  if (locale === 'pt') return NAMES_PT[slug] ?? englishName
  return englishName
}
